name: Test Workflow

on:
  push:
    branches:
      - main  # lub twoja gałąź, na której pracujesz

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Workflow działa poprawnie!"

      - name: Test npm version
        run: node -v
